/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  gcc_rx_project                         */
/*      FILE         :  gcc_rx_project.cpp                     */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void) {

	/*****************************************************************************************
	I/Oピンの設定
		ブザー用IOポートの設定
	*****************************************************************************************/
	//ブザー関連
	PORTB.PDR.BIT.B5 = 1;
	
	/*****************************************************************************************
	メインプログラム
		ブザーON
	*****************************************************************************************/
	int i = 0;
	while(1){
		PORTB.PODR.BIT.B5 = 1;
		for(i = 0; i < 100; i++);
		PORTB.PODR.BIT.B5 = 0;
		for(i = 0; i < 100; i++);
  }
return 0;
}